import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/lib/auth-provider'
import CartProvider from '@/context/cart-context'
import CartSheet from '@/components/cart-sheet'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-Br'>
      <body className={`${inter.className} bg-appBackground`}>
        <AuthProvider>
          <CartProvider>
            {children}
            <CartSheet />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
